name: Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.5.1
              with:
                  node-version: 18
                  registry-url: https://registry.npmjs.org/
            - run: npm ci --force
            - run: npm test
